### PR TITLE
Creating prototype menüs

### PR DESCRIPTION
**Pull request by roadsidepicnic1**
First version of GameMenus

### CODE REVIEW

**Comment by roadsidepicnic1** [comment]
Dont know why test failes, i formatted the code.

**Comment by Marcel-John** [comment]
this might  help with the format warning:
https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d

**Review by Mesaying — APPROVED** [review]
The art looks great :)

**Review by Marcel-John — APPROVED** [review]
Looks Good

**Pull request merged**
